// final-project/src/components/TimerForm/index.jsx
import React, { useState } from "react";
import { Link } from "react-router-dom";
import TimerListItem from "../TimerListItem";

const TimerForm = () => {
  const [label, setLabel] = useState("");
  const [time, setTime] = useState(0);
  const [timers, setTimers] = useState([]);
  const handleSubmit = ($event) => {
    $event.preventDefault();
    addTimer(label, time);
    setTime(0);
    setLabel("");
  };


  const addTimer = (label, time) => {
    setTimers([...timers, {label, time}]);
  }
  return (
    <>
      <h2>Add a timer:</h2>
      <form onSubmit={($event) => handleSubmit($event)}>
        <div className="form-group">
          <label htmlFor="label">Label:</label>
          <input
            type="text"
            name="label"
            value={label}
            className="form-control"
            onChange={(e) => setLabel(e.target.value)}
          />
        </div>
        <div className="form-group">
          <label htmlFor="time">Time (seconds):</label>
          <input
            type="number"
            name="time"
            value={time}
            className="form-control"
            onChange={(e) => setTime(e.target.value)}
          />
        </div>
        <button
          type="submit"
          className="btn btn-primary"
          disabled={!label || !time}
        >
          Submit
        </button>
      </form>
      {
        timers.map((timer, index) => <TimerListItem label={timer.label} time={timer.time} key={index}/>)
      }
      {
        !!timers.length && <Link to='start' state={timers}><button>START</button></Link>
      }
    </>
  );
};

export default TimerForm;

// final-project-angular/src/app/timer-form/timer-form.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { TimersService } from '../services/timers.service';
import { timer } from '../types/timer.types';

@Component({
  selector: 'app-timer-form',
  templateUrl: './timer-form.component.html',
  styleUrls: ['./timer-form.component.scss']
})
export class TimerFormComponent implements OnInit {
  label: string = '';
  time: number = 0;
  timers: timer[] = [];

  constructor(
    private router: Router,
    private timerService: TimersService
  ) {

  }
  ngOnInit(): void {
    this.timers = this.timerService.getTimers();
  }

  addTimer(event: any) {
    console.log(event);
    event.preventDefault();
    this.timerService.addTimer({label: this.label, time: this.time});
    this.resetFields();
    this.timers = this.timerService.getTimers();
  }

  resetFields() {
    this.time = 0;
    this.label = '';
  }

  startTimer() {
    this.router.navigate(['/start'])
  }
}

<form (submit)="addTimer($event)">
  <mat-form-field>
    <mat-label for="label">Label</mat-label>
    <input matInput [(ngModel)]="label" name="label">
  </mat-form-field>
  <mat-form-field>
    <mat-label for="time">Time</mat-label>
    <input matInput [(ngModel)]="time" type="number" name="time">
  </mat-form-field>
  <button mat-fab type="submit" color="primary" [disabled]="!label || !time"><mat-icon>add</mat-icon></button>
</form>

<div class="timers-list list-group">
  <div class="timer list-group-item" *ngFor="let timer of timers">
    {{timer.label}}: {{timer.time}}
  </div>
</div>
<button mat-raised-button color="accent" [disabled]="timers.length === 0" (click)="startTimer()">START</button>
